services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - client
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: production
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/club.db
      - REDIS_URL=redis://redis:6379
      - SPICEDB_ENDPOINT=spicedb:50051
      - SPICEDB_TOKEN=${SPICEDB_TOKEN:-hmu_production_secret_key_change_me}
    volumes:
      - server_data:/app/data
    depends_on:
      redis:
        condition: service_healthy
      spicedb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    expose:
      - "5173"
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
        reservations:
          memory: 128M
          cpus: "0.1"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"
        reservations:
          memory: 64M
          cpus: "0.1"
    command: redis-server --appendonly yes --maxmemory 100mb --maxmemory-policy allkeys-lru

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: spicedb
      POSTGRES_USER: spicedb
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-spicedb_secure_password_change_me}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spicedb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

  spicedb:
    image: authzed/spicedb:latest
    command: serve --grpc-preshared-key "${SPICEDB_TOKEN:-hmu_production_secret_key_change_me}" --http-enabled
    expose:
      - "8080"  # HTTP API
      - "50051" # gRPC API
    environment:
      - SPICEDB_DATASTORE_ENGINE=postgres
      - SPICEDB_DATASTORE_CONN_URI=postgresql://spicedb:${POSTGRES_PASSWORD:-spicedb_secure_password_change_me}@postgres:5432/spicedb?sslmode=disable
      - SPICEDB_DATASTORE_CONN_POOL_READ_MAX_OPEN=20
      - SPICEDB_DATASTORE_CONN_POOL_WRITE_MAX_OPEN=10
      - SPICEDB_DATASTORE_CONN_POOL_READ_MIN_OPEN=5
      - SPICEDB_DATASTORE_CONN_POOL_WRITE_MIN_OPEN=2
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

volumes:
  redis_data:
  server_data:
  postgres_data:
