name = "gloss-bot"
compatibility_date = "2024-10-11"

[vars]
DISCORD_APP_ID = "1371585113435017386"
DISCORD_GUILD_ID = "1020747207353311252"
DISCORD_PUBLIC_KEY = "5e5cc8a95ab2f39a35b896e87477a5a56effc9c141c4d3fdc9672757f9345e3e"
DISCORD_OAUTH_DESTINATION = "https://gloss-bot.carl-vitullo-cloudflare.workers.dev/oauth"
# DISCORD_OAUTH_DESTINATION = "https://6013-68-160-221-91.ngrok-free.app/oauth"
MAILJET_PUBLIC = "8eb3e314b0cd8d03efe9fb7bd76d9277"
# GOOGLE_SA_PRIVATE_KEY="don't forget to manually add this to Cloudflare"

[[kv_namespaces]]
binding = "gloss-bot"
id = "22b3910c9b7445eb8f0e70df89bfe9ea"

[observability]
enabled = true
