/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: string;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: string;
  userId: string;
}

export interface AuditLog {
  action: string;
  created_at: Generated<string | null>;
  entity_id: number | null;
  entity_type: string;
  id: Generated<number | null>;
  metadata_json: string | null;
  new_values_json: string | null;
  old_values_json: string | null;
  user_ip: string | null;
  user_session_id: string | null;
}

export interface EventAttendance {
  attendance_source: Generated<string | null>;
  checked_in_at: string | null;
  checked_out_at: string | null;
  event_id: number;
  id: Generated<number | null>;
  member_id: number;
  notes: string | null;
}

export interface EventbriteEvents {
  capacity: number | null;
  category_id: string | null;
  created_at: Generated<string | null>;
  description_html: string | null;
  description_text: string | null;
  end_local: string | null;
  end_timezone: string | null;
  end_utc: string | null;
  eventbrite_id: string;
  flags: Generated<number | null>;
  format_id: string | null;
  id: Generated<number | null>;
  last_synced_at: Generated<string | null>;
  name_html: string | null;
  name_text: string | null;
  organizer_json: string | null;
  raw_eventbrite_data: string | null;
  show_remaining: Generated<number | null>;
  start_local: string | null;
  start_timezone: string | null;
  start_utc: string | null;
  status: Generated<number | null>;
  subcategory_id: string | null;
  sync_hash: string | null;
  ticket_classes_json: string | null;
  updated_at: Generated<string | null>;
  url: string | null;
  venue_json: string | null;
}

export interface Events {
  created_at: Generated<string | null>;
  created_by_member_id: number | null;
  description: string | null;
  end_datetime: string;
  eventbrite_id: string | null;
  eventbrite_url: string | null;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  max_capacity: number | null;
  name: string;
  required_membership_types: string | null;
  start_datetime: string;
  updated_at: Generated<string | null>;
}

export interface EventsAttendance {
  attendance_source: Generated<number | null>;
  check_in_method: string | null;
  created_at: Generated<string | null>;
  event_id: number;
  eventbrite_attendee_id: string | null;
  eventbrite_order_id: string | null;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  marketing_source: string | null;
  member_id: number | null;
  notes: string | null;
  registration_date: string | null;
  ticket_type: string | null;
  updated_at: Generated<string | null>;
}

export interface EventsEventbriteLink {
  created_at: Generated<string | null>;
  event_id: number;
  eventbrite_event_id: number;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  last_synced_at: string | null;
  sync_direction: Generated<string | null>;
  sync_errors: string | null;
  sync_status: Generated<string | null>;
}

export interface EventsMarketing {
  blurb: string | null;
  created_at: Generated<string | null>;
  created_by_member_id: number | null;
  email_preview_text: string | null;
  email_subject: string | null;
  event_id: number;
  flags: Generated<number | null>;
  hashtags: string | null;
  id: Generated<number | null>;
  key_selling_points: string | null;
  marketing_images_json: string | null;
  primary_marketing_copy: string | null;
  secondary_marketing_copy: string | null;
  seo_description: string | null;
  seo_title: string | null;
  social_media_copy: string | null;
  updated_at: Generated<string | null>;
}

export interface EventsVolunteers {
  arrival_time: string | null;
  checked_in_at: string | null;
  checked_out_at: string | null;
  confirmed_at: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  coordinator_notes: string | null;
  created_at: Generated<string | null>;
  departure_time: string | null;
  equipment_needed: string | null;
  event_id: number;
  flags: Generated<number | null>;
  hours_worked: number | null;
  id: Generated<number | null>;
  member_id: number;
  role: string;
  skills_required: string | null;
  special_instructions: string | null;
  updated_at: Generated<string | null>;
  volunteer_notes: string | null;
}

export interface ExternalIntegrations {
  external_data_json: string | null;
  external_id: string;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  last_synced_at: string | null;
  member_id: number;
  system_name: string;
}

export interface MemberMemberships {
  created_at: Generated<string | null>;
  end_date: string | null;
  external_payment_reference: string | null;
  id: Generated<number | null>;
  member_id: number;
  membership_type_id: number;
  notes: string | null;
  payment_status_id: number | null;
  start_date: string;
}

export interface Members {
  access_level: Generated<number | null>;
  created_at: Generated<string | null>;
  date_added: Generated<string | null>;
  email: string;
  first_name: string;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  last_name: string;
  preferred_name: string | null;
  pronouns: string | null;
  sponsor_notes: string | null;
  updated_at: Generated<string | null>;
}

export interface MembershipTypes {
  benefits_json: string | null;
  created_at: Generated<string | null>;
  description: string | null;
  exclusive_group_id: string | null;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  name: string;
  price_cents: number | null;
}

export interface PaymentStatuses {
  created_at: Generated<string | null>;
  description: string | null;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  name: string;
  sort_order: Generated<number | null>;
}

export interface Session {
  createdAt: string;
  expiresAt: string;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface SyncOperations {
  created_at: Generated<string | null>;
  error_message: string | null;
  external_id: string | null;
  id: Generated<number | null>;
  member_id: number | null;
  operation_type: string;
  payload_json: string | null;
  platform: string;
  processed_at: string | null;
  status: string;
}

export interface User {
  createdAt: string;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  updatedAt: string;
}

export interface Verification {
  createdAt: string | null;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: string | null;
  value: string;
}

export interface DB {
  account: Account;
  audit_log: AuditLog;
  event_attendance: EventAttendance;
  eventbrite_events: EventbriteEvents;
  events: Events;
  events_attendance: EventsAttendance;
  events_eventbrite_link: EventsEventbriteLink;
  events_marketing: EventsMarketing;
  events_volunteers: EventsVolunteers;
  external_integrations: ExternalIntegrations;
  member_memberships: MemberMemberships;
  members: Members;
  membership_types: MembershipTypes;
  payment_statuses: PaymentStatuses;
  session: Session;
  sync_operations: SyncOperations;
  user: User;
  verification: Verification;
}
