/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AuditLog {
  action: string;
  created_at: Generated<string | null>;
  entity_id: number | null;
  entity_type: string;
  id: Generated<number | null>;
  metadata_json: string | null;
  new_values_json: string | null;
  old_values_json: string | null;
  user_email: string | null;
  user_id: string | null;
  user_ip: string | null;
  user_session_id: string | null;
}

export interface Events {
  created_at: Generated<string | null>;
  created_by_member_id: number | null;
  description: string | null;
  end_datetime: string;
  eventbrite_id: string | null;
  eventbrite_url: string | null;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  max_capacity: number | null;
  name: string;
  start_datetime: string;
  updated_at: Generated<string | null>;
}

export interface EventsMarketing {
  blurb: string | null;
  created_at: Generated<string | null>;
  created_by_member_id: number | null;
  email_preview_text: string | null;
  email_subject: string | null;
  event_id: number;
  flags: Generated<number | null>;
  hashtags: string | null;
  id: Generated<number | null>;
  key_selling_points: string | null;
  marketing_images_json: string | null;
  primary_marketing_copy: string | null;
  secondary_marketing_copy: string | null;
  seo_description: string | null;
  seo_title: string | null;
  social_media_copy: string | null;
  updated_at: Generated<string | null>;
}

export interface EventsVolunteers {
  arrival_time: string | null;
  checked_in_at: string | null;
  checked_out_at: string | null;
  confirmed_at: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  coordinator_notes: string | null;
  created_at: Generated<string | null>;
  departure_time: string | null;
  equipment_needed: string | null;
  event_id: number;
  flags: Generated<number | null>;
  hours_worked: number | null;
  id: Generated<number | null>;
  member_id: number;
  role: string;
  skills_required: string | null;
  special_instructions: string | null;
  updated_at: Generated<string | null>;
  volunteer_notes: string | null;
}

export interface ExternalIntegrations {
  external_data_json: string | null;
  external_id: string;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  last_synced_at: string | null;
  member_id: number;
  system_name: string;
}

export interface Members {
  access_level: Generated<number | null>;
  created_at: Generated<string | null>;
  date_added: Generated<string | null>;
  email: string;
  first_name: string;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  last_name: string;
  preferred_name: string | null;
  pronouns: string | null;
  sponsor_notes: string | null;
  updated_at: Generated<string | null>;
}

export interface Session {
  createdAt: string;
  expiresAt: string;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface SyncOperations {
  created_at: Generated<string | null>;
  error_message: string | null;
  external_id: string | null;
  id: Generated<number | null>;
  member_id: number | null;
  operation_type: string;
  payload_json: string | null;
  platform: string;
  processed_at: string | null;
  status: string;
}

export interface User {
  createdAt: string;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  updatedAt: string;
}

export interface DB {
  audit_log: AuditLog;
  events: Events;
  events_marketing: EventsMarketing;
  events_volunteers: EventsVolunteers;
  external_integrations: ExternalIntegrations;
  members: Members;
  session: Session;
  sync_operations: SyncOperations;
  user: User;
}
