/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: string;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: string;
  userId: string;
}

export interface AuditLog {
  action: string;
  created_at: Generated<string | null>;
  entity_id: number | null;
  entity_type: string;
  id: Generated<number | null>;
  metadata_json: string | null;
  new_values_json: string | null;
  old_values_json: string | null;
  user_email: string | null;
  user_id: string | null;
  user_ip: string | null;
  user_session_id: string | null;
}

export interface Events {
  created_by_member_id: number | null;
  description: string | null;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  name: string;
  url: string | null;
}

export interface EventsFlags {
  event_id: number;
  expires_at: string | null;
  flag_id: string;
  granted_at: Generated<string | null>;
  granted_by: string | null;
  metadata: string | null;
}

export interface Flags {
  created_at: Generated<string | null>;
  id: string | null;
  name: string;
  updated_at: Generated<string | null>;
}

export interface Members {
  created_at: Generated<string | null>;
  date_added: Generated<string | null>;
  email: string;
  first_name: string;
  flags: Generated<number | null>;
  id: Generated<number | null>;
  last_name: string;
  preferred_name: string | null;
  pronouns: string | null;
  sponsor_notes: string | null;
  updated_at: Generated<string | null>;
}

export interface MembersFlags {
  expires_at: string | null;
  flag_id: string;
  granted_at: Generated<string | null>;
  granted_by: string | null;
  member_id: string;
  metadata: string | null;
}

export interface Session {
  createdAt: string;
  expiresAt: string;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: string;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  updatedAt: string;
}

export interface Verification {
  createdAt: string | null;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: string | null;
  value: string;
}

export interface DB {
  account: Account;
  audit_log: AuditLog;
  events: Events;
  events_flags: EventsFlags;
  flags: Flags;
  members: Members;
  members_flags: MembersFlags;
  session: Session;
  user: User;
  verification: Verification;
}
