version: 2
updates:
  # Root workspace dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "vcarl"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript"
          - "turbo"
          - "knip"
          - "husky"
          - "lint-staged"
        update-types:
          - "minor"
          - "patch"

  # Server workspace dependencies
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "vcarl"
    labels:
      - "dependencies"
      - "server"
      - "automated"
    commit-message:
      prefix: "deps(server)"
      include: "scope"
    groups:
      server-dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript"
          - "tsx"
          - "vitest"
          - "@vitest/*"
        update-types:
          - "minor"
          - "patch"
      server-production:
        patterns:
          - "express"
          - "kysely"
          - "better-sqlite3"
          - "cors"
          - "helmet"
          - "morgan"
          - "winston"
          - "axios"
          - "uuid"
        update-types:
          - "patch"

  # Client workspace dependencies
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "vcarl"
    labels:
      - "dependencies"
      - "client"
      - "automated"
    commit-message:
      prefix: "deps(client)"
      include: "scope"
    groups:
      client-dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript"
          - "vite"
          - "@vitejs/*"
          - "vitest"
          - "@vitest/*"
          - "tailwindcss"
          - "postcss"
          - "autoprefixer"
        update-types:
          - "minor"
          - "patch"
      react-ecosystem:
        patterns:
          - "react"
          - "react-dom"
          - "react-router-dom"
          - "@tanstack/react-query*"
        update-types:
          - "patch"

  # E2E tests workspace dependencies
  - package-ecosystem: "npm"
    directory: "/tests"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "vcarl"
    labels:
      - "dependencies"
      - "testing"
      - "automated"
    commit-message:
      prefix: "deps(tests)"
      include: "scope"
    groups:
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "vcarl"
    labels:
      - "github-actions"
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "actions/*"
          - "docker/*"
        update-types:
          - "minor"
          - "patch"

  # Docker
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "vcarl"
    labels:
      - "docker"
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "deps(docker)"

  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"  
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "vcarl"
    labels:
      - "docker"
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "deps(docker)"